double signinpad = 0;
double padd = 0;
double sedpadd = 0;
double sedpadd1 = 0;
double foldpadd = 0;
double routpadd = 0;
double dropwid = 0;
double walLeft0 = 0;
double walleft = 0;
double walib3 = 0;
double walib1 = 0;
double walibsp = 0;
double proleftp = 0;
double setpad1 = 0;
double setpad2 = 0;
double setpad3 = 0;
double setpad4 = 0;
double setpad5 = 0;
double setpad6 = 0;

bool status = false;
bool status2 = false;
bool status3 = false;
bool status4 = false;
bool status5 = false;
bool status6 = false;
Map log = {};
Map values = {};

double dashtime = 0;
double routewidth = 0;
double bus1 = 0;
double bus2 = 0;
double history = 0;
double pading = 0;
double aboutimage = 0; //about image
double aboutcont = 0; //about container
double aboutimg = 0; //about imge height
